### ISSUE TITLE
ready pds-engineering to go public

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#135]
- [x] archive MCM Artifacts
- [x] remove MCM pages (need go-ahead. Will check in tomorrow.)
- [x] update Sitemap
- [x] add clearance number to footer (need CL #)
- [x] remove login

additional tasks [below](https://github.com/NASA-PDS/pdsen-operations/issues/135#issuecomment-876025433)

**Comment by acyu** [comment]
- [ ] update pds-engineering footer to match current JPL footer template

**Comment by jordanpadams** [comment]
@elawsgh @c-suh per the MCM Artifacts is there a plan to link to the GDrive where those docs now reside? We have kept these docs online in the past because once in a while node folks ask for them. I am just thinking if we include a link to the GDrive (which is blocked to only certain people), it would at least give people the breadcrumbs. If not, it isn't a huge deal.

**Comment by elawsgh** [comment]
@jordanpadams I'd prefer not to do that. Everything on a public site should be publicly available IMHO. Nodes should already know about the GDrive as all the meeting notes are shared there. Once they are populated, we or Laurie can send out email to nodes to let them know.

**Comment by jordanpadams** [comment]
closing this as completed. remaining task is here: https://github.com/NASA-PDS/portal-tasks/issues/14
