### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mars2020_meda

### ISSUE THREAD

**Issue by ghost** [NASA-PDS/operations#151]
## Discipline Node Information

**Delivering Node**: ATM

**NSSDCA Delivery Package**: 
[mars2020_meda_v1.0_20210908.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/7131454/mars2020_meda_v1.0_20210908.tar.gz)

**Validation report**: 
[medaval.txt](https://github.com/NASA-PDS/pdsen-operations/files/7131586/medaval.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by jordanpadams** [comment]
@Astro-Joni can you please upload the validation report or link to it online?

**Comment by Astro-Joni** [comment]
Jordan Padams ***@***.***> wrote:

>
***@***.*** can you please upload the validation report or link to it online?
>

I did!  The 'box' showed it in place before I closed it. 
But I'll try again.

Joni

**Comment by jordanpadams** [comment]
@Astro-Joni looks good now! that was weird...

**Comment by c-suh** [comment]
@Astro-Joni, this set has been posted for NSSDCA processing. Beginning tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020_meda_v1.0_20210908

**Comment by smclaughlin7** [comment]
@Astro-Joni @c-suh @jordanpadams The NSSDCA ingested this SIP, and we're presently archiving it to tape.  However, the Deep Archive software did not include this primary basic product in the SIP manifest file because the **_VID specified in the collection inventory (1.0) does not match the VID in the label (01.0)_**, and therefore we have not ingested or archived it:

Product LID: urn:nasa:pds:mars2020_meda:document:release_notes
Label URL: [https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/Mars2020/mars2020_meda/document/release_notes.xml](url)
Inventory URL: [https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/Mars2020/mars2020_meda/document/collection_document_inventory.csv](url)

If you want us to ingest and archive this version 1.0 of the release notes product now, please correct the VID in the product label (01.0 -> 1.0) then run the Deep Archive software on the corrected bundle and submit the resulting package to EN as usual.  Otherwise, please correct the label VID in the next release (and submission) of this accumulating bundle.  Thanks!

**Comment by jordanpadams** [comment]
thanks @smclaughlin7 .

as an FYI, unfortunately, even though logically you'd think we could "assume" 1.0==01.0 in terms of numbers, the VID is actually a string,  which means it needs to be an exact match.

@c-suh it looks like validate was not executed with the `pds4.bundle` rule. this is necessary to ensure issues like this don't pop-up. can we update our procedures to look for this. the easiest way to spot check this is in the report summary.

```
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
```

**Comment by Astro-Joni** [comment]
smclaughlin7 ***@***.***> wrote:

>
>If you want us to ingest and archive this version 1.0 of the release notes product now, please correct the VID in the product label (01.0 -> 1.0) then run the Deep Archive software on the corrected bundle and submit the resulting package to EN as usual.  Otherwise, please correct the label VID in the next release (and submission) of this accumulating bundle.  Thanks!
>

We have it fixed and will resubmit it.  Thanks!

Joni

**Comment by c-suh** [comment]
@jordanpadams understood; don't just check for errors. Another way is to check the parameters at the top of the report, correct?
```
Parameters:
   Targets                       [file:/X:/data/example.xml]
   Rule Type                     pds4.bundle
```
I will check #152 and follow-up as needed.

**Comment by smclaughlin7** [comment]
@jordanpadams Thanks. Actually it's good to know VID is treated as a string, e.g., 01.0 != 1.0.  As a sanity check on NSSDCA's finding, I had downloaded the collection in question and validated it as a `pds4.collection`, which flagged the mismatch with warnings.

**Comment by jordanpadams** [comment]
thanks for checking that @smclaughlin7 . I was going to do so myself and file a bug if we were converting to a decimal :-)

**Comment by smclaughlin7** [comment]
> So I presume we need to re-run validation on the (slightly) improved bundle?  I'll ask Lyle which rule he's been using when he does the validation...he does the validation as part of the process when we receive data.

@Astro-Joni  Hi, Joni: Catherine should confirm but I recommend re-validating the slightly improved MEDA bundle #151. @c-suh

**Comment by c-suh** [comment]
@Astro-Joni, I'm in agreement with Stef: please re-run validation on the improved bundle with the relevant rule specifier before resubmitting it. Thank you!

**Comment by c-suh** [comment]
resubmitted in #154, #248, (#251 - duplicate submission of #248), and #254.

**Comment by c-suh** [comment]
@tinagueth kindly pointed out this package has been archived. Thank you!
