### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mgs_tes_recalib_atmos

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#186]
## Discipline Node Information

**Delivering Node**: PDS_ATM

**NSSDCA Delivery Package**: 
[mgs_tes_recalib_20211112.tar.gz](https://github.com/NASA-PDS/operations/files/7530744/mgs_tes_recalib_20211112.tar.gz)

**Validation report**: 
[mgs_tes_recalib_atmos.txt](https://github.com/NASA-PDS/operations/files/7530745/mgs_tes_recalib_atmos.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:mgs_tes_recalib_atmos_v1.0_20211112

**Comment by smclaughlin7** [comment]
@tinagueth @c-suh @jordanpadams This SIP failed NSSDCA front-end validation because the prolog in the bundle product uses a lowercase value for UTF-8 encoding:

`<?xml version="1.0" encoding="utf-8"?>`

Tiffany Holden here at the NSSDCA determined the SaxParser, which is one of the tools used during our validation, doesn’t like the lowercase encoding value and is throwing an exception.  Since the bundle XML is valid (Oxygen has no problem with the prolog and successfully validates the product), she will tweak our validation software to account for the lowercase encoding values.

After she implements the fix, we'll reprocess the SIP through our front-end.  You don't have to fix or resubmit anything.  I'll post here when we've reprocessed this SIP.

Thanks for your patience, and Happy Thanksgiving!

**Comment by tinagueth** [comment]
@smclaughlin7 @c-suh @jordanpadams Thank you for the information. I passed it along to the PDS ATM group and Lyle Huber did wonder if this might cause a validation fail with NSSDCA.

Happy Thanksgiving!

**Comment by smclaughlin7** [comment]
@tinagueth @c-suh @jordanpadams  Good news re: SIP LID

    urn:nasa:pds:system_bundle:product_sip_deep_archive:mgs_tes_recalib_atmos_v1.0_20211112

Tiffany tweaked our front-end software to allow lowercase encoding values in the prolog, e.g. `<?xml version="1.0" encoding="utf-8"?>`.  She successfully reprocessed the SIP through our front-end; it will be ingested and archived next week.

**Comment by c-suh** [comment]
@tinagueth the AIP/SIP set for `mgs_tes_recalib_atmos` has been archived.
