### ISSUE TITLE
load stage registries

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/operations#196]
On:
- pds-gamma
- beta on AWS
- staging on AWS
- production on AWS

Log in a pds4

Follow instruction on ~/pds-registry-ingest/README_LOCAL.txt

**Comment by c-suh** [comment]
Made a few minor corrections. Originals are saved as <filename>.bck
- ~/pds-registry-ingest/README_LOCAL.txt
- ~/pds-registry-ingest/README.md

@tloubrieu-jpl , the .txt file says to "Follow instruction on prerequisite" in the README. Confirming that this does not include the user quickstart? If I am supposed to follow the quickstart, I do not know updates or edits I'm supposed to make to the new conf file.

---

Quick status: followed the prerequisite (without user quickstart. One package, pystache, hasn't been installed). Ran the command to delete the registry and got 
```
Elasticsearch URL: https://xxxxx
Deleting index registry
[ERROR] 10,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
```
Do not know how to otherwise check status of registry.

**Comment by tloubrieu-jpl** [comment]
This ticket is a duplicate of pds-operations#196
