### ISSUE TITLE
Use zenhub sprints instead of milestones

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/operations#208]
to do before end of 2021

**Comment by jordanpadams** [comment]
This is already being done for the backlogs. Is there something else that needs to happen?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl ☝️

**Comment by jordanpadams** [comment]
closing this as done since the sprints are already active for the org and most (if not all tickets) have been tagged for their applicable sprints.
<img width="637" alt="Screen Shot 2021-12-17 at 11 15 46 AM" src="https://user-images.githubusercontent.com/33492486/146596350-86bd205a-4182-464e-a995-d0fd845ae58c.png">
