### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mgs_tes_recalib_atmos

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#263]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[mgs_tes_recalib_20220531.tar.gz](https://github.com/NASA-PDS/operations/files/8808128/mgs_tes_recalib_20220531.tar.gz)

* **Validation report**: 
[mgs_tes_recalib_atmosv2.txt](https://github.com/NASA-PDS/operations/files/8808132/mgs_tes_recalib_atmosv2.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:mgs_tes_recalib_atmos_v2.0_20220531

**Comment by smclaughlin7** [comment]
@tinagueth @c-suh @jordanpadams NSSDCA ingest rejected this submission because the [SIP manifest](https://pds.nasa.gov/data/pds4/manifests/2022/mgs_tes_recalib_atmos_v2.0_20220531_sip_v1.0.tab) contains 6 entries with the same data object URL but different LIDVIDs.  That's because the data object  [https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/mgs_tes_recalib_atmos/data_derived_surf-emissivity/color_bar_CBRedYlBu.png](https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/mgs_tes_recalib_atmos/data_derived_surf-emissivity/color_bar_CBRedYlBu.png) is identified as a component of 6 different observational products, each with a different LIDVID:
```
urn:nasa:pds:mgs_tes_recalib_atmos:data_derived_surf-emissivity:hematite::1.0
urn:nasa:pds:mgs_tes_recalib_atmos:data_derived_surf-emissivity:rms_error::1.0
urn:nasa:pds:mgs_tes_recalib_atmos:data_derived_surf-emissivity:surf_emiss_25::1.0
urn:nasa:pds:mgs_tes_recalib_atmos:data_derived_surf-emissivity:surf_emiss_9::1.0
urn:nasa:pds:mgs_tes_recalib_atmos:data_derived_surf-emissivity:surface_type1::1.0
urn:nasa:pds:mgs_tes_recalib_atmos:data_derived_surf-emissivity:surface_type2::1.0
```

PDS4 Standards Reference 2A.3 states “digital objects which comprise observational data may be used in one and only one product”, that is one LID.  [Validate Issue 245](https://github.com/NASA-PDS/validate/issues/245) addresses this issue but it's ETA is TBD.

In the interim, would it be possible to archive the digital object “color_bar_CBRedYlBu.png” as either

1.  a separate basic product, then link to it via a new internal reference in the labels of the 6 rejected product, or
2. 6 different digital objects with slightly different names, one for each of the 6 rejected products?

These solutions are just off the top of my head. There may be others.  I'd appreciate your thoughts on tweaking this bundle so that the NSSDCA could ingest it sooner rather than later.  Thanks!

**Comment by smclaughlin7** [comment]
@tinagueth  Might you have an update on this issue and resubmitting a new deep archive package for this bundle?  No rush; just wanted to tag up. Thanks!

**Comment by tinagueth** [comment]
@smclaughlin7 @c-suh Thanks for the checking in. Currently, we still do not have an update for this. Lyle has been quite busy, which will continue this month, but it is moving up on his to-do list. Hopefully I can resubmit it by the end of the year.

**Comment by smclaughlin7** [comment]
@tinagueth Thanks for this update. Much appreciated.

**Comment by tinagueth** [comment]
@smclaughlin7 @c-suh I just resubmitted this bundle (see #321). Lyle said he did the second recommended solution provided by above. Thanks

**Comment by smclaughlin7** [comment]
@tinagueth @c-suh Thanks Tina, and Lyle too!, for revising those six products and resubmitting as (see https://github.com/NASA-PDS/operations/issues/321).  Much appreciated.

**Comment by tinagueth** [comment]
@c-suh The AIP/SIP set for the revised version of this bundle (#321) has been archived, hence I am closing this issue as well.
