### ISSUE TITLE
Deployment of Registry Loader Tools and Initial Ingestion of Engineering Node Registry on Latest AWS Deployment

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/operations#270]
## 💡 Description

- [x] @c-suh installs  standalone hsarvest and registry-manager latest stable version on pds-gamma
- [x] @rchenatjpl installs standalone harvest and registry-manager latest stable version as described on https://nasa-pds.github.io/registry/install/install.html (in /usr/local/build11/ -->  /usr/local/applications).
- [x] @jimmie creates a temporary login for Richard to access OpenSearch
- [X]  @rchenatjpl loads some data and set the proper archive status (archived). Starting with context products.
- [X] @rchenatjpl check that the data has been properly ingested in OpenSearch
- [X] @tloubrieu-jpl / @rchenatjpl check that ingested data is accessible through the web api http://pds.nasa.gov/api/search/1.0/products?limit=100

List of products to ingest:
- [ ] PDS3 context products
- [ ] PDS4 context products
- [ ] EN-managed documents (directories under here: https://pds.nasa.gov/data/pds4/documents/ . isn't https://pds.nasa.gov/data/pds4/documents/bundle_system.xml in the wrong place)
- [ ] Update current process to ingest everything when archive is updated (@rchenatjpl )
https://wiki.jpl.nasa.gov/display/PDSEN/Data+Release+Procedures ("Cloud" section)

**Comment by rchenatjpl** [comment]
@tloubrieu-jpl or anyone: sorry for the late start. 1) Am I really installing on pdscloud-prod2? Shouldn’t I do this on pdscloud-gamma? 2) On ~pds4 on both machines, java -version says 1.8. Should I install my own jdk 1.11 in my local dir? Thanks

**Comment by c-suh** [comment]
@tloubrieu-jpl jdk11 wasn't available on the pdscloud-* machines, so I've installed it on gamma to start and will have it on the others by the end of today. A note that installing it to where the existing java is was not possible because it required root access, so I did it to the pds4 home directory as you suggested above. Another note that I've also installed `jenv` to manage multiple java versions (leaving the existing jdk8 as global and will make jdk11 the default in the directories that Richard will create/install), since I imagine that a few of our older tools might not play well with this java version.

**Comment by rchenatjpl** [comment]
OK, I shoved harvest and registry into pds4cloud-prod1:/usr/local/build11/. In the Description at the top of this page, I don't understand what this means: "in /usr/local/build11/ --> /usr/local/applications". Should I build a softlink in the latter? Hopefully, it doesn't matter.

What's the URL for Kibana on pds4cloud-prod1? I did get the password. How does Kibana know where the registry sits?

**Comment by jimmie** [comment]
The Opensearch dashboard (fka Kibana) is associated with the particular Opensearch domain. For the EN registry, this is at: https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com/_dashboards

**Comment by rchenatjpl** [comment]
Thanks. So I assume something's not configured correctly:

[pds4@pdscloud-prod1 test]$ ls -l directories.xml 
-rw-r--r--. 1 pds4 pds 1866 Jun 16 15:07 directories.xml
[pds4@pdscloud-prod1 test]$ pwd
/home/pds4/test
[pds4@pdscloud-prod1 test]$ /usr/local/build11/harvest-3.6.0/bin/harvest -c  directories.xml 
[SUMMARY] Reading configuration from /data/home/pds4/test/directories.xml
[SUMMARY] Output directory: /tmp/harvest/out
[SUMMARY] Elasticsearch URL: http://localhost:9200, index: registry
[INFO] Connecting to Elasticsearch
[ERROR] Connection refused

**Comment by rchenatjpl** [comment]
Wait, should I create the registry first?

[pds4@pdscloud-prod1 ~]$ /usr/local/build11/registry-manager-4.4.0/bin/registry-manager create-registry
Elasticsearch URL: http://localhost:9200
Creating index...
   Index: registry
  Schema: /usr/local/build11/registry-manager-4.4.0/elastic/registry.json
  Shards: 1
Replicas: 0
[ERROR] Connection refused

localhost:9200 is some elastic search thing? How do I start that, presumably on pdscloud-prod1? Thanks

**Comment by jimmie** [comment]
No, the registry is already created. Just need to load the data.

The Opensearch endpoint (i.e. the 'Elasticsearch URL') for the production EN registry is https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443

**Comment by rchenatjpl** [comment]
@jimmie @tloubrieu-jpl Ah. So in the harvest config file, I should change
  <registry url="http://localhost:9200" index="registry" />
to
  <registry url="https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443" index="registry" />

I hope that's right. Now I'm getting
[pds4@pdscloud-prod1 test]$ /usr/local/build11/harvest-3.6.0/bin/harvest -c  directories.xml 
[SUMMARY] Reading configuration from /data/home/pds4/test/directories.xml
[SUMMARY] Output directory: /tmp/harvest/out
[SUMMARY] Elasticsearch URL: https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443, index: registry
[INFO] Connecting to Elasticsearch
[ERROR] method [GET], host [https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443], URI [/registry/_mappings], status line [HTTP/1.1 403 Forbidden]
{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet because no resource-based policy allows the es:ESHttpGet action"}

So I need to set the user? I don't see an option on the harvest command line or in the config file

**Comment by tloubrieu-jpl** [comment]
@rchenatjpl the link @jimmie sent is on the old documentation, the new one is here https://nasa-pds.github.io/registry/

For the authentication management in harvest job configuration file you can refer to 
https://nasa-pds.github.io/registry/user/harvest_job_configuration.html#registry-integration

**Comment by tloubrieu-jpl** [comment]
@jimmie I redirected all the page of the obsolete repository to the new documentation, see https://nasa-pds.github.io/pds-registry-app/operate/harvest.html so that anyone who kept these pages in their bookmark is redirected to the new page. That was true, from the landing page of the documentation but not from every pages

**Comment by rchenatjpl** [comment]
@tloubrieu-jpl @jimmie 
[pds4@pdscloud-prod1 test]$ /usr/local/build11/harvest-3.6.0/bin/harvest -c  directories.xml 
[SUMMARY] Reading configuration from /data/home/pds4/test/directories.xml
[SUMMARY] Output directory: /tmp/harvest/out
[SUMMARY] Elasticsearch URL: https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443, index: registry
[INFO] Connecting to Elasticsearch
[ERROR] method [GET], host [https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443], URI [/registry/_mappings], status line [HTTP/1.1 403 Forbidden]
{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet because no resource-based policy allows the es:ESHttpGet action"}

[pds4@pdscloud-prod1 test]$ grep auth directories.xml 
  <registry url="http://localhost:9200" index="registry" auth="/path/to/auth.cfg" />
  <registry url="https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443" index="registry" auth="/home/pds4/test/auth.txt" />

[pds4@pdscloud-prod1 test]$ cat /home/pds4/test/auth.txt
# true - trust self-signed certificates; false - don't trust.
trust.self-signed = true
user = xxx
password = xxx

**Comment by jimmie** [comment]
We need to have pdscloud-prod1 and pdscloud-prod2 added to the OpenSearch whitelist. I will file a ticket to have that done.

**Comment by rchenatjpl** [comment]
oh, thank goodness, i assumed it was user error

**Comment by c-suh** [comment]
@rchenatjpl, @tloubrieu-jpl, and @viviant100, it sounds like the EN-specific documentation wasn't looked at, which means that (1) the java version isn't set and (2) the installation isn't in the new deployment directory we had the SAs set up. Should I address these or work with @rchenatjpl on these? Also confirming that this should be on only one of the production machines and not both?

**Comment by rchenatjpl** [comment]
Did I miss steps? That's entirely possible. It's hard for me to chase down links and remember where I am.

**Comment by tloubrieu-jpl** [comment]
@rchenatjpl I think you need to:
-  install in /usr/local/applications
- use jdk11 

@c-suh how popular is 'jenv' ? Is it widely used in Joel's environments ? I never used it and was happy with setting JAVA_HOME. If we use it, which I am not against, we need to document that and make it a standard in our deployments because I would worry if sometimes we set the java_home manually, sometimes we use Jen. That can become messy.

Thanks

**Comment by c-suh** [comment]
@tloubrieu-jpl pardon, "Joel's environments"? `jenv` seems to be used fairly commonly to manage multiple java versions, and I think it's much friendlier than `alternatives` or `sdkman`, because you can set local environments once (like with `pyenv`) and forget about it, opposed to having to manually switch between versions. However, I had done this (installed a version manager rather than switching entirely to version 11), because I assumed that upgrading the entire system to jdk11 would have broken some of our older tools. Apologies for not posing this as a question or making it more obvious at the end of my [comment above](https://github.com/NASA-PDS/operations/issues/270#issuecomment-1156940854). So, should we upgrade entirely to jdk11 or use a java version manager?

Additionally, I did not see anything in the public documentation about configuring any endpoints, but is there anything we need to let the SAs know to use the new versions of these tools? There was the related question in the Slack channel regarding the new deployment directory (and possible standardized procedure), because currently, any upgrades to these tools requires letting the SAs know to re-point to the new versions. 

As for documentation, regarding setting the java version locally, I included this as step 2 of "[Installation](https://wiki.jpl.nasa.gov/display/PDSEN/Standalone+Harvest#StandaloneHarvest-Installation)" for both Standalone Harvest and Registry Manager. Regarding the initial installation and setup of `jenv`, I kept personal notes but did not post it in the internal wiki. Should I create a page for now under the Software page, and it can be moved later to a page or section that is not for PDS-specific software?

@rchenatjpl yup, I linked the documentation in Slack channel, but I see now that it's hardly visible amidst all the other blue of the mentions. Too many conveniences cluttered together. Here is the internal documentation for [Standalone Harvest](https://wiki.jpl.nasa.gov/display/PDSEN/Standalone+Harvest) and [Registry Manager](https://wiki.jpl.nasa.gov/display/PDSEN/Registry+Manager). These can also be gotten to from the Registry section of [Software Installation and Deployment Guides](https://wiki.jpl.nasa.gov/display/PDSEN/Software+Installation+and+Deployment+Guides)

**Comment by c-suh** [comment]
@tloubrieu-jpl and @viviant100 as suggested then agreed upon, I have removed `jenv` and instead inserted a line to call another script which has the jdk11 path. This has been tested on gamma and the documentation has been updated for when Richard installs this on production. I've noticed that the **pds** account on gamma has a `pds-registry-app-1.0.2` which contains `harvest-3.5.1` and `registry-manager-4.3.0`. Should this be left alone or deleted?

**Comment by viviant100** [comment]
I would suggest to delete it if it's not in use.

**Comment by c-suh** [comment]
@rchenatjpl I saw your comment on the internal Registry Manager wiki page, and it sounds like it installed successfully! Please confirm if
1. standalone harvest is installed on cloud prod1
2. registry manager is installed on cloud prod1
3. anything else?

**Comment by rchenatjpl** [comment]
@c-suh @tloubrieu-jpl @jimmie Those two are installed, but the next question of course is how to hook everything up. Is there a way to check if registry-manager is already running? If I should run registry-manager on prod1 myself, is there a way to check if OpenSearch is running? 

So I tried:
[pds4@pdscloud-prod1 test]$ registry-manager create-registry
Elasticsearch URL: http://localhost:9200
Creating index...
   Index: registry
  Schema: /usr/local/applications/registry-manager/elastic/registry.json
  Shards: 1
Replicas: 0
[ERROR] Connection refused

Hopefully that means registry-manager is running already on the machine I'm supposed to connect to. Is that localhost:9200 or the long amazonaws URL that Jimmie sent a while ago? I tried the latter. In ~pds4/test/directories.xml:
`  <registry url="https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443" index="registry" auth="/home/pds4/test/auth.txt" />
`
and that auth file does exist and does hold what Jimmie sent. I did not change the password - I just want stuff to work once before doing so. Anyway,
`[pds4@pdscloud-prod1 test]$ harvest -c directories.xml 
[SUMMARY] Reading configuration from /data/home/pds4/test/directories.xml
[SUMMARY] Output directory: /tmp/harvest/out
[SUMMARY] Elasticsearch URL: https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443, index: registry
[INFO] Connecting to Elasticsearch
[ERROR] method [GET], host [https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443], URI [/registry/_mappings], status line [HTTP/1.1 403 Forbidden]
{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet because no resource-based policy allows the es:ESHttpGet action"}
`
And for good measure I tried localhost:9200
`[pds4@pdscloud-prod1 test]$ diff directories.xml dir2.xml
22,23c22,23
<   
<   <registry url="https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443" index="registry" auth="/home/pds4/test/auth.txt" />
---
>   <registry url="http://localhost:9200" index="registry" />
>   
[pds4@pdscloud-prod1 test]$ harvest -c dir2.xml
[SUMMARY] Reading configuration from /data/home/pds4/test/dir2.xml
[SUMMARY] Output directory: /tmp/harvest/out
[SUMMARY] Elasticsearch URL: http://localhost:9200, index: registry
[INFO] Connecting to Elasticsearch
[ERROR] Connection refused
`
I tried yet another version with the auth file attached to localhost, but same thing. I'll keep plugging away, but  hopefully someone can spot the problem easily. Thanks

**Comment by jordanpadams** [comment]
@rchenatjpl 

> Is there a way to check if registry-manager is already running?

As a general idea, registry-manager is just a command-line tool for interacting with OpenSearch (aka the Registry). It is a command-line tool, similar to validate or the legacy search-core. So it just runs when you tell it to run. That being said, if you want to check if you or someone else is running it right now:

```
ps aux | egrep registry-manager
```

> Is that localhost:9200 or the long amazonaws URL that Jimmie sent a while ago?

I believe it is the long URL, but I will leave that to @jimmie

**Comment by jimmie** [comment]
@rchenatjpl - the admins have enabled access to Opensearch from en-prod. I need to test. If that works, they will enable it from all of the JPL IP addresses.

To answer your question regarding accessing Opensearch, you will need to use the URI: https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com/

**Comment by jimmie** [comment]
I have verified that I can access en-prod from pdscloud-prod1 and pdscloud-prod2. @rchenatjpl - you should now be unblocked in this respect.

**Comment by rchenatjpl** [comment]
@jimmie @tloubrieu-jpl @c-suh Regarding the last message, I'm hoping a 2-minute glance will show something obvious to one of you. If not, I'll muck around. Thanks

**Comment by jimmie** [comment]
@rchenatjpl - how are you querying Opensearch? I'm seeing documents in there.

`curl -u pdsadmin -X GET "https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com/registry/_count"
{"count":106,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0}}`

**Comment by jimmie** [comment]
No, that works for me. What login are you using?

**Comment by rchenatjpl** [comment]
No login. Oh, I replaced the escaped &amp; with &, and now I see "hits". Thanks, @jimmie

**Comment by rchenatjpl** [comment]
@tloubrieu-jpl I'm getting back into this, and the configuration confuses me again. From pdscloud-prod1, harvest's config file points to
  registry url="https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443" index="registry" auth="/home/pds4/test/auth.txt"
When I re-harvest something I harvested a month ago, I correctly get many error messages 'Skipping registered product...', e.g.
  [WARN] Skipping registered product urn:nasa:pds:orex.radioscience::1.0

Now,  how do I manipulate the registry? And where? I tried
```
  % curl --get 'https://pds.nasa.gov/api/search/1.0/products/urn:nasa:pds:orex.radioscience::1.0' --header 'Accept: application/json'
  {"request":"/products/urn:nasa:pds:orex.radioscience::1.0","message":"The lidvid urn:nasa:pds:orex.radioscience was not found"}
```
So I replaced https://pds.nasa.gov with the URL in the harvest config file
```
  % curl --get 'https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443/api/search/1.0/products/urn:nasa:pds:orex.radioscience::1.0' --header 'Accept: application/json'
  {"error":"no handler found for uri [/api/search/1.0/products/urn:nasa:pds:orex.radioscience::1.0] and method [GET]"}
```

I'm going to want to view and delete entries. I should be using these curl commands? Should I also be able to do so using registry-manager commands? If so, how do I point registry-manager to the OpenSearch that harvest  uses? Thanks

**Comment by viviant100** [comment]
redirect above inquiry to @jimmie

**Comment by jimmie** [comment]
You were correct in sending the api/search/1.0 to pds.nasa.gov - Opensearch itself (search-en-prod*) doesn't understand that format. I imagine it's not being returned because the archive_status has not been promoted to 'archived' which you need to do using registry-manager.

Registry-manager should use the same endpoint that you used in Harvest and is specified on the command line using the -es switch. Run `registry-manager -help` to see the available command line options.

**Comment by rchenatjpl** [comment]
@jimmie  Is https://pds.nasa.gov/api/search/ accessing other registries as well as the one I'm mucking with? I ingested LIDs urn:nasa:pds:asteroid_polarimetric_database*, and before promoting them to 'archived', they already showed up in the URL above. And if I delete all entries from my registry, those LIDs still show, even in a private browser.

**Comment by jimmie** [comment]
@rchenatjpl - yes, that endpoint accesses all of the registries via Opensearch cross-cluster search (CCS). Unfortunately, with this architecture there is no way to isolate EN since EN's Opensearch is the one with CCS enabled.

**Comment by rchenatjpl** [comment]
No problem, thanks, I'm just trying to account for what I'm seeing. 
@jordanpadams I'm going to create 1 more fake bundle with slightly weird stuff, then I'll call my stuff done unless you want more. ETA tonight. I would use real bundles, but the ones that are workable are already registered.

**Comment by jordanpadams** [comment]
@rchenatjpl that sounds great! once you get that test data, can you hand it over to @c-suh so she can upload it here: https://pds.nasa.gov/data/pds4/test-data/custom-datasets/

**Comment by rchenatjpl** [comment]
@c-suh Sorry to stick you with this.
  pdscloud-prod1://home/pds4/contextSubset.tgz
has 2 similar toy bundles, both with PDS4 context products, a bundle, collections, and documents, as requested at the top of this issue. The tester should harvest the first bundle, check that OpenSearch does not have the LIDs from the second bundle not in the first bundle, harvest the second bundle, see those LIDs.

**Comment by rchenatjpl** [comment]
I just noticed the PDS3 request. I don't know the innards of how a PDS3 catalog file gets into the current database. I run 'catalog -mingest' to do that. Those calls operationally are buried within ~pds4/catalog/*/update-procedure.txt, which are scripts despite the file extension.

I did successfully ingest /data/pds4/context-pds3, the context products equivalent to the PDS3 catalog files, but that may not be what you want.

**Comment by c-suh** [comment]
@rchenatjpl, @jordanpadams, and @viviant100 sorry in turn, but it's unclear to me what I'm supposed to do.
- I don't see contextSubset.tgz on any of the usual 3 machines under either the pds or pds4 user. Is this what I would upload, as is, to https://pds.nasa.gov/data/pds4/test-data/custom-datasets/?
- Am I the tester? I've dabbled in multiple procedures, but harvest is not a recent one, so please either point me to the resources/documentation to follow or to the person(s) that I'm supposed to pass information along to.

**Comment by jordanpadams** [comment]
@rchenatjpl @c-suh sorry for the confusion here. I lost track of this ticket and it seems like we are headed down a rabbit hole we really didn't want to go.

the premise of this ticket and [it's parent](https://github.com/nasa-pds/registry/issues/61) was to deploy all the tools and actually ingest all of the EN-managed data into the registry. not to test the registry beyond a very simple initial smoke test of "can I communicate with and ingest something". From the comments above, it looks like the smoke test is completed, so the final steps should be for us to get all this data ingested and update our procedures in the future to include this ingestion.

@rchenatjpl can we please:
- [ ] remove all of the data we have ingested thus far (@jimmie can help with what this command is if you can't find it in the docs)
- [ ] actually operationally configure and execute harvest on the following data we manage:
  - [ ] PDS3 context products
  - [ ] PDS4 context products
  - [ ] EN-managed documents (directories under here: https://pds.nasa.gov/data/pds4/documents/ . isn't https://pds.nasa.gov/data/pds4/documents/bundle_system.xml in the wrong place)
- [ ] update release procedures to run harvest on these data any time they are updated

**Comment by jordanpadams** [comment]
also, per @jimmie's comment above for searching the registry for EN data, we should be able to query via our node_id, but I have had some trouble figuring out how to search that field (or any field names really) via a URL endpoint. will get back to you.

**Comment by jordanpadams** [comment]
@jimmie any ideas on how we could query the registry by node id?

**Comment by jimmie** [comment]
node is given by the term ops:Harvest_Info/ops:node_name. I thought the API provides the ability to add a 'query' as a URI query parameter that could include a specific value for node_name

**Comment by jordanpadams** [comment]
@jimmie copy. the PDS API definitely supports this, I just haven't quite been able to figure out the appropriate syntax/escaping in order to make the query work via curl. I will keep poking.

**Comment by rchenatjpl** [comment]
@jordanpadams @viviant100 Regarding "PDS3 Context Products" in the Description at the very top of this ticket, do you want the PDS3 context products ingested? Currently, they're hidden outside EN presumably because we don't want anyone to reference any of them. These are the ones that begin urn:nasa:pds:context_pds3:..., and they're sitting in /data/pds4/1700/PDS3_context_bundle_20161220/. Or do you have something else in mind for "PDS3 Context Products"? I'll assume I shouldn't ingest them, but if you want me to, I'll do it, though I'll have to create a bundle.xml and collection*.xml

**Comment by jordanpadams** [comment]
@rchenatjpl just to verify, do you know how this information is then getting populated if not from those context products? https://pds.nasa.gov/ds-view/pds/viewInstrumentProfile.jsp?INSTRUMENT_ID=ISSW&INSTRUMENT_HOST_ID=VG1

**Comment by rchenatjpl** [comment]
Wait, you're probably right that that info is coming from the PDS3 context products, though there must be some special handling somewhere to suppress the LID from showing up. Less probable but possible is that that info comes directly from the PDS3 catalog files or the PDS3 database, but that database is so tenuous.

**Comment by rchenatjpl** [comment]
@jimmie I hope you're the right person, Jimmie. I harvested the files at /data/pds4/system_bundle/, but when I try to set the archive status to archived, I get this output:
```
[INFO] Setting product status. LIDVID = urn:nasa:pds:system_bundle::1.0, status = archived
[ERROR] [_doc][urn:nasa:pds:system_bundle:product_sip_deep_archive:gbo.ast.catalina.survey_v1.0_20220420_delta_20220908200751165540::1.0]: document missing
```
I can see that LID in the registry via https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com/registry/_search?q=lid:*gbo.ast.catalina.survey_v1.0_20220420_delta_20220908200751165540
But I must have something else crossed. Any ideas? Thanks

**Comment by jimmie** [comment]
@rchenatjpl - Are you pointing to production? That Opensearch URI you provided is production. The Opensearch for en-gamma is [here](https://search-en-delta-cxbnln2tudbdrclt4nr7scdmpu.us-west-2.es.amazonaws.com/) . If I query that, it says the registry index doesn't exist. When you run registry-manager to create the registry schema and populate the data, please be sure your configuration is pointing to the proper Opensearch.

**Comment by rchenatjpl** [comment]
@jimmie Hi, Jimmie, yes, I am trying to put that stuff into production. I'm tasked with putting 1) the PDS4 context products, 2) the PDS3 context products, and 3) this stuff into production. I think I succeeded with 1. I haven't tried 2 yet because I'm not sure what will happen if there's no bundle.xml or collection*.xml for those. Do you know? And 3, that's this problem. Thanks

**Comment by jimmie** [comment]
OK thanks @rchenatjpl. Sorry for my misunderstanding of which Opensearch instance you were intending to use. 

But looking at things more closely, I'm not sure your initial ingestion worked correctly - if you compare the id of the match that comes back from your Opensearch query with what you're looking for:

in Opensearch: 
urn:nasa:pds:system_bundle:product_aip:gbo.ast.catalina.survey_v1.0_20220420_delta_20220908200751165540::1.0

your id: 
urn:nasa:pds:system_bundle:product_sip_deep_archive:gbo.ast.catalina.survey_v1.0_20220420_delta_20220908200751165540::1.0

**Comment by rchenatjpl** [comment]
@jimmie cr@p. thanks

**Comment by rchenatjpl** [comment]
@jordanpadams I briefly again doubted whether the context_pds3 files were ingested into the current registry, but now I'm more
 sure they are because 1) searching for "ISSW" returns some results with no LID (presumably the PDS3) and some with LID (i.e. migrated into a proper PDS4 context product), and 2) search returns data sets, which only exist in u:n:p:context_pds3:...

**Comment by viviant100** [comment]
@rchenatjpl we have a section here for release procedures: https://wiki.jpl.nasa.gov/display/PDSEN/Data+Release+Procedures.  Feel free to use the "[Cloud](https://wiki.jpl.nasa.gov/display/PDSEN/Cloud)" section underneath for your procedure.

**Comment by jordanpadams** [comment]
thanks @rchenatjpl per the PDS3 vs PDS4 context products, we probably need to scrub all of these and make sure we do not have duplicates between the PDS3 and PDS4 versions. I assume we have both right now because of the PDS3/PDS4 filter, but for the distinction doesn't really make sense.

**Comment by rchenatjpl** [comment]
@jordanpadams I may be going about this wrong for what you want. Am I looking for context products that are exactly the same except for u:n:p:context vs u:n:p:context_pds3? There won't be many. Am I looking for all u:n:p:context and u:n:p:context_pds3 that point to the same physical thing? I'll guess so. If so, I think what I should give you is a mapping of the u:n:p:context_pds3 things to the u:n:p:context things. Or something else?

**Comment by rchenatjpl** [comment]
1. Ignoring u:n:p:c*:attribute and :class - what are they for?
2. Ignoring these with no equivalent in the other:
  u:n:p:context:agency
  u:n:p:context:airborne
  u:n:p:context_pds3:dataset
  u:n:p:context_pds3:subscription
  u:n:p:context:resource (only 3: ladee, maven, phoenix)
  u:n:p:context_pds3:resource (5609)
  u:n:p:context:service
  u:n:p:context_pds3:volume
  u:n:p:context_pds3:volumeset
3. u:n:p:context:telescope and the facilities that go with them will be tough because in PDS3, a each facility x telescope was a single insthost, I think.

**Comment by jordanpadams** [comment]
@rchenatjpl this is great! eventually I think we want to deprecate the "PDS3" version, and have only the PDS4 version available. having both seems like duplicate content and I feel like the system doesn't quite make sense for this. that being said, happy to hear other ideas if we think we should keep both separate. maybe @jshughes or @rsjoyner have thoughts

**Comment by jordanpadams** [comment]
Closing this as done for the time being until we identify what data is missing and the procedures that need to be updated
