### ISSUE TITLE
[ldd-release] LDD-Speclib LDD Version:1.4 IM Version:1.18

### ISSUE THREAD

**Issue by scholes-ds** [NASA-PDS/operations#285]
* **Is the LDD IngestLDD in Github?**  Yes

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?**  Yes

* **Need-by date**: Next couple of weeks would be nice

* **Need-by date rationale**:  

The recent LDD updates this month have been my first attempts at uploading a data dictionary update. It appears the Ingest LDD was updated, but the actions were skipped and the other files were not generated as part of the release. I think I must have messed up a step. Can someone from EN take a look at this? I just made a minor update to correct the IM and release date in the Ingest file. Rather than pushing forward on my own with (https://pds-data-dictionaries.github.io/development/ldd-release.html), I would appreciate someone checking out the updates. Feel free to contact me directly.

Thanks,
Dan 

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**:

* **PDS4 IM version to release with**:

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github

* **LDD**: _Name of LDD Ready for release_
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by jordanpadams** [comment]
@scholes-ds per the Github Actions and the PR merge, it looks like the LDD generation worked as expected.

<img width="1049" alt="Screen Shot 2022-07-28 at 5 08 51 PM" src="https://user-images.githubusercontent.com/33492486/181657124-590ea6ce-1fcf-47e6-8740-5247635288b3.png">

and you can see the merge in main was successful:

https://github.com/pds-data-dictionaries/ldd-speclib/tree/main/build/development/c7e03eb8c31e02b63b7316c7aa1f922b9e8a75eb
https://github.com/pds-data-dictionaries/ldd-speclib/tree/main/build/development/c7e03eb8c31e02b63b7316c7aa1f922b9e8a75eb/1.18.0.0

In order to tag a release manually in Github (e.g. we don't do it for you at our nominal 6-month build schedule), take a look at this process: https://pds-data-dictionaries.github.io/development/ldd-release.html#preparing-a-release . Specifically the section on how to "Tag a Release in Github". You will need to create a new release branch, which will re-build the LDDs, place them in the release directory, and tag a release in your releases here: https://github.com/pds-data-dictionaries/ldd-speclib/releases

Then you can provide a link to the specific release contained the ZIP of the version you want the ops team to push out.

**Comment by c-suh** [comment]
SPECLIB_1I00_1400 has been successfully released at https://github.com/pds-data-dictionaries/ldd-speclib/releases/tag/1I00_1400.
