### ISSUE TITLE
[ldd-request] Create new repository for existing LDD "hyb2"

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#296]
* **Local Data Dictionary Name:** Hayabusa2

* **Namespace ID ~~Requested~~:** hyb2

* ~~**Discipline or Mission LDD?**~~ 

* ~~**Steward Organization Name:**~~ 

* **LDD Steward Name:** Carol Neese

* **LDD Steward Email:** neese@psi.edu

* **LDD Stewardship Team Members:** @neese, ?

* **LDD Description:** The Hayabusa2 Dictionary (hyb2) contains classes, attributes and rules specific to the Hayabusa2 Mission and its instruments.

* ~~**Rationale for creation of new LDD:**~~

---

**Engineering Details**
- [ ] Complete **relevant section of** [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by neese** [comment]
@c-suh Thanks for getting me started.  I'd like to leave the stewardship team at just me for now.  At a future time I may add someone on the mission side, but for now I will just use the repo to submit the IngestLDD provided by the mission.  You have crossed out "Discipline or Mission LDD", but of course it is a Mission LDD so you could put that.  Otherwise this looks good.

**Comment by c-suh** [comment]
@neese, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-hyb2! Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started, and let me know if you have any questions!
