### ISSUE TITLE
[ldd-release] Apollo LDD Version: 1.0.0.0 IM Version:1.18.0.0

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#303]
* **Is the LDD IngestLDD in Github?** Yes

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** Yes

In the next 2-3 weeks would be nice. 

A new dataset that uses this Mission LDD was deployed at GEO on 9/26/22, and this Mission LDD has not yet been released.

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**: https://github.com/pds-data-dictionaries/ldd-apollo/releases/tag/1I00_1000

* **PDS4 IM version to release with**: 1.18.0.0

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github

* **LDD**: _Name of LDD Ready for release_
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
Hello @jennifergward, my apologies for the delay, and congratulations on successfully tagging a release in the repo! The LDD files have passed validation, but I have noticed that the IngestLDD.xml filename uses "Apollo" rather than the highly recommended "APOLLO". Please address this such that the casing matches the schema/schematron then re-trigger [the process](https://pds-data-dictionaries.github.io/development/ldd-release.html#tag-a-release-in-github) to tag a release in GitHub (the existing release might have to first be deleted). I will then post this without further delay and do my best to keep this within the requested 2-3 week timeframe!

A note that GitHub can be particular about case-sensitive changes to filenames. This is easily circumvented by using `git mv` (as described in the first example of [this article](https://daily-dev-tips.com/posts/git-basics-help-my-case-sensitive-filename-changes-dont-commit/)), but please let me know if you run into any issues, and I will do my best to assist. Thank you!

**Comment by jennifergward** [comment]
Hi @c-suh. I've attempted to re-trigger the process to tag a release, but it doesn't seem to be working. I followed the steps [here](https://pds-data-dictionaries.github.io/development/ldd-release.html#tag-a-release-in-github), but I don't see the tagged release in step 10. I'm not sure what I'm doing wrong. Please help!

**Comment by jordanpadams** [comment]
@jennifergward sorry about that. if you are trying to re-release the same version it GitHub, you will need to make sure you delete the Release and the Tag from both tabs you find on [this page](https://github.com/pds-data-dictionaries/ldd-apollo/releases/). Otherwise the build will see this release was already made and will fail so that you do not overwrite.

<img width="376" alt="Screen Shot 2022-10-11 at 9 06 20 AM" src="https://user-images.githubusercontent.com/33492486/195143327-0c47be17-0751-4ae3-91a5-f4b44434b7c5.png">

**Comment by jordanpadams** [comment]
@jennifergward head to the [tags page](https://github.com/pds-data-dictionaries/ldd-apollo/tags), select the appropriate tag, and then select delete tag.

right now, you have to delete the release first before you can delete the tag.

**Comment by c-suh** [comment]
@jennifergward thank you for making that change and being so willing to navigate github! Correct - you did not need to submit another release request, and this LDD is now posted at https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#apollo!
