### ISSUE TITLE
Prep dLDDs for review and release

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#306]
## 💡 Description

Per our schedule, we need to generate the LDDs for review for the next build.

https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-PrepdLDDsforStewardReview

**Comment by c-suh** [comment]
@jordanpadams for each dLDD, the github action job for "Generate and Validate (1.19.0.0)" is erroring because of an "Invalid argument list" for the LDDTool. Here are a couple example logs: [imaging's](https://github.com/pds-data-dictionaries/ldd-img/actions/runs/3268095141/jobs/5374104822) and [cart's](https://github.com/pds-data-dictionaries/ldd-cart/actions/runs/3268323986/jobs/5374600881). Do I message Steve about this?

**Comment by c-suh** [comment]
Bug has been addressed and am awaiting a new tag/release of the tool.

**Comment by c-suh** [comment]
This has successfully run and completed! Pull requests for IM 1.19.0.0 have been created for each discipline LDD.
