### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:insight_twins

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#324]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[insight_twins_20230104.tar.gz](https://github.com/NASA-PDS/operations/files/10346070/insight_twins_20230104.tar.gz)

* **Validation report**: 
[twins_bundlev15.txt](https://github.com/NASA-PDS/operations/files/10346075/twins_bundlev15.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by smclaughlin7** [comment]
@c-suh Hi Catherine, Could you please process/post this delivery when you get a chance?  Thanks!

**Comment by c-suh** [comment]
@smclaughlin7 oops; certainly. @tinagueth my apologies for the delay! This set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:insight_twins_v3.1_20230104

---

Stef, is it helpful for you to know ahead of time which year directory these are in? We've got the first of the 2023 packages!

**Comment by tinagueth** [comment]
@c-suh @smclaughlin7 No worries! I have been catching up with several smaller projects since coming back from break last week. Thanks for the update though :)

**Comment by smclaughlin7** [comment]
> @smclaughlin7 oops; certainly. @tinagueth my apologies for the delay! This set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:
> 
> SIP LID:
> 
>     * urn:nasa:pds:system_bundle:product_sip_deep_archive:insight_twins_v3.1_20230104
> 
> 
> Stef, is it helpful for you to know ahead of time which year directory these are in? We've got the first of the 2023 packages!

@c-suh Every night around 5am our automated SIP puller scans https://pds.nasa.gov/data/pds4/manifests/ and its yearly subdirectories and pulls any new SIPs (just the SIP xml label files, e.g. \*sip\*.xml), so we don't need to know ahead of time which year directory a SIP is in.  However when you post a SIP (i.e., Deep Archive package) the year is important because the package needs to be put in the yearly subdirectory specified by the <manifest_url> element in the SIP xml label file.

For example for this https://github.com/NASA-PDS/operations/issues/324, the SIP xml label file insight_twins_v3.1_20230104_sip_v1.0.xml specifies the associated SIP manifest table file lives here:

`<manifest_url>https://pds.nasa.gov/data/pds4/manifests/2023/insight_twins_v3.1_20230104_sip_v1.0.tab</manifest_url>
`

So after we auto-download the SIP xml label, our front-end process cracks it open then uses the <manifest_url> to download the SIP manifest table file.  (Our front-end and ingest processes both work off the contents of the manifest file.)  If the Deep Archvie package is stored in a different yearly subdirectory, we will still auto-download the SIP xml label but our front-end process will not be able to find the manifest file and will reject that SIP and not pass it to our ingest process.

Whew!  (My apologies for this long explanation.)

**Comment by tinagueth** [comment]
@c-suh all SIP/AIP for this bundle have been archived
