### ISSUE TITLE
[ldd-release] NEAR LDD Version:1.18.0.0 IM Version:IF00-1I00

### ISSUE THREAD

**Issue by klopez1313** [NASA-PDS/operations#349]
* **Is the LDD IngestLDD in Github?** _Yes 

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** _Yes _

* **02-15-2023**:

* **NEAR LDD needed for completion of NEAR GRS PDS3 to PDS4 migration**:

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**:

* **PDS4 IM version to release with**:

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github

* **LDD**: _Name of LDD Ready for release_
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
Hello @klopez1313, and thank you for submitting this request! I am hoping to clarify which LDDs you would like released and the locations of these LDDs. So, for the first question - are the requested LDDS for IM versions 1.15.0.0-1.18.0.0 (1F00-1I00), LDD version 1.0.0.0?

Regarding the second question (the location of these LDDs), it was not specified in the description above if the requested LDDs to be released are in or not in GitHub, so I took a look at the [ldd-near GitHub repository](https://github.com/pds-data-dictionaries/ldd-near). I do not see any tagged [releases](https://github.com/pds-data-dictionaries/ldd-near/releases), but I do see one LDD for IM version: 1.18.0.0 (1I00), LDD version: 1.0.0.0 under the `build/development/*` directory. (I am discounting the example LDD for IM version: 1.17.0.0 (1H00) under the `build/release` directory.) I can create a release for the existing LDD for IM version **1.18.0.0 (1I00)**. Are there LDDs elsewhere (not in the GitHub repository) for IM versions **1.15.0.0-1.17.0.0 (1F00-1H00)**?

As an aside, I've often found these issue comments difficult to both read and write with the formatting and markup, and the 'Preview' tab at the top of these comment boxes is extremely helpful for me. I just want to share this tip in case you're not aware of it! (I'm attaching a screenshot of this comment as an example.)

---

![Screenshot 2023-02-10 at 11 29 37 AM](https://user-images.githubusercontent.com/18314609/218182012-30aae3b0-b273-4cd7-af0b-9d7a263cbcb3.jpg)

**Comment by klopez1313** [comment]
Hi Catherine,
Thank you for the helping me out, I'm still learning how git hub works. I
got someone to help me create a new release. I would like to please use
release/1.15-18.0.0_1.0.0.0

Hopefully I got it all right! Please let me know if I need to
change anything.

Thank you,
Kristina

**Comment by c-suh** [comment]
Hi Kristina (@klopez1313), and thank you for creating a release! You are certainly braver than I am because GitHub definitely has a learning curve, and had I anticipated that you'd jump in so quickly, I would've pointed you to [our documentation](https://pds-data-dictionaries.github.io/development/mission-ldds.html#release-a-mission-ldd) on the LDD release process. My apologies if there were any difficulties that could've been eased by having the documented information at hand. As it is, the [current release](https://github.com/pds-data-dictionaries/ldd-near/releases/tag/release%2F1.15-18.0.0_1.0.0.0) holds a copy of the entire repository rather than just the LDD files, and we also encourage a single release per IM/LDD version combination rather than a single release which encapsulates multiple IM/LDD versions.

If you are up for it, would you try the following? Follow the instructions detailed in step 1 of the ["Release a Mission LDD" process](https://pds-data-dictionaries.github.io/development/mission-ldds.html#release-a-mission-ldd) to create a release for just 1.15.0.0_1.0.0.0. If this is successful, please repeat step 1 to manually prepare a release for 1.16.0.0_1.0.0.0, 1.17.0.0_1.0.0.0, and 1.18.0.0_1.0.0.0 as well. (For 1.18.0.0_1.0.0.0, please ensure that the LDD files for NEAR 1.8.0.0_1.0.0.0 are in the repository, as I do not currently see them present.) If you have any questions or issues anywhere during this process, please feel free to let me know!

**Comment by c-suh** [comment]
Ah, thank you for that relevant detail! In that case, @klopez1313, please make sure to add the files for 1.18.0.0_1.0.0.0 before going through step 1 of Releasing a Mission LDD (which is to [manually prepare a release in GitHub](https://pds-data-dictionaries.github.io/development/ldd-release.html#preparing-a-release)) just the one time (as opposed to 4 times). Two additional notes:
- you do not need to do step 2 of Releasing a Mission LDD, as you have already manually submitted the release request (with this GitHub issue)
- in case it's noticed that the first attempted release (LDD-NEAR release/1.15-18.0.0_1.0.0.0) is gone, it is because I removed it (no GitHub voodoo)

**Comment by klopez1313** [comment]
Hi Catherine,
Sorry this took so long but I believe I have fixed the issues on github to
get this released hopefully?
Please let me know if there is anything else i need to do.

**Comment by c-suh** [comment]
@klopez1313 that was excellent! I have validated and posted all 4 LDDs to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#near. I am closing this issue, but let me know if there are any problems, and we will either reopen or create a new issue ticket. Thank you!

**Comment by klopez1313** [comment]
Thank you so much!
