### ISSUE TITLE
[lid-request] urn:nasa:pds:context:investigation:mission.viper

### ISSUE THREAD

**Issue by mnhughes** [NASA-PDS/operations#382]
* **PDS4 LID:** 
* urn:nasa:pds:context:investigation:mission.viper
* urn:nasa:pds:context:instrument_host:spacecraft.gll
* urn:nasa:pds:context:instrument:viper.nirvss
* urn:nasa:pds:context:instrument:viper.msolo
* urn:nasa:pds:context:instrument:viper.nss
* urn:nasa:pds:context:instrument:viper.trident

* **LID Type:** Context
  
* **Mission:** VIPER

* **Responsible Node:** geo

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Hi, Maddie, pardon me if you've thought through this stuff.

The last part of the spacecraft LID, .gll, bothers me. You already know the inst LIDs have format:
  u:n:p:c:i:<something1>.<something2>
For instruments on spacecraft, something1 always (I can't think of exceptions, though I could check if desired) comes from u:n:p:c:instrument_host:spacecraft.<something1> rather than from u:n:p:c:investigation:mission.<something1>. So I'd suggest
  u:n:p:c:instrument_host:spacecraft.viper
However, is ".gll" the Griffin lander? I saw that on wikipedia. I don't know understand what the different parts of this mission are or how they're connected, e.g. are VIPER and CLPS separate missions, or is VIPER one of the CLPS missions? In my mind, If CLPS is the mission, that would make some sense in my brain:
  u:n:p:c:inv:mission.clps
  u:n:p:c:insthost:viper
  u:n:p:c:insthost:to_2a
  ...
with the mission context product referencing multiple instrument hosts, which is normal, like Viking with its 2 orbiters + 2 landers.

Another complication: you asked if I knew of any context LIDs for viper, and I didn't. However, I didn't think to check the bundle LIDs. Susie a year ago asked for many VIPER LIDs that probably are just bundle LIDs but maybe were meant to be context LIDs, though I wouldn't think she'd make a mistake like that. Or maybe she wanted to request a context LID this way?  On https://pds-engineering.jpl.nasa.gov/content/bundle-lids, type "viper" in the search box, and the bundle LIDs seem to match up with the insts and the other context products. I dunno.

**Comment by rchenatjpl** [comment]
Oh, wait, I obviously didn't read issue 381 first. I have the same concern about the end of the instrument_host LID. I guess it's still possible that all these are 1 big mission (there are more to come, right, like clps_to_19c?). Or maybe ignore that and treat them all as separate missions as you have them. But my instrument_host concern would still stand

**Comment by mnhughes** [comment]
Hi Richard, 

VIPER and to_2ab are all under the 'CLPS' program umbrella (they are being delivered by a commercial company) but should still be considered different missions. The commercial company names the lander, which is why for to_2ab it is "Peregrine Lunar Lander" and for VIPER it is "Griffin Lunar Lander". The instrument host for to_2ab could be changed to u:n:p:c:insthost:clps_to_2ab_pll, and we can change the instrument LIDs accordingly. What are your thoughts? Susie's reserved bundle LIDs look correct, I think there was just some miscommunication and context LIDs were never reserved. I will need get back to you regarding the VIPER instrument host LIDs - two may be needed - I will let you know.

**Comment by mnhughes** [comment]
Hi Richard, The VIPER rover is actually the instrument host (instead of the lander) so these will be the context LIDs for VIPER: 
urn:nasa:pds:context:investigation:mission.viper
urn:nasa:pds:context:instrument_host:spacecraft.viper 
urn:nasa:pds:context:instrument:viper.nirvss
urn:nasa:pds:context:instrument:viper.msolo
urn:nasa:pds:context:instrument:viper.nss
urn:nasa:pds:context:instrument:viper.trident
urn:nasa:pds:context:instrument:viper.vis  (new addition)
urn:nasa:pds:context:instrument:viper.rover (new addition)

**Comment by mnhughes** [comment]
Hi Richard, are there any issues with these LIDs?

**Comment by rchenatjpl** [comment]
Yes, those look fine. I'll get them on the context LID list, though the actual context products would be definitive.
After reinserting this into my brain, I'm currently thinking of these (viper and all the clps_to_somewhere) as separate missions, at least when it comes to content products.

**Comment by mnhughes** [comment]
Hi Richard, I am close to having these context products ready, but they will have reference texts that won't have a DOI until later this year. Should I wait until they are totally finished to send them to you?

**Comment by mnhughes** [comment]
Got it, sounds good. I'll wait until they are finished to send them over (unless the data provider insists otherwise, but I think they will be fine with this).

**Comment by thareUSGS** [comment]
@mnhughes @rchenatjpl - I missed these were in the works. To support a forthcoming geospatial viper archive, I created a quick take at the mission.viper text. But I am happy to see another version already completed published. I did cheat a little and used AI to help with the text.

That is all we need for now - just mission.viper (none of the planned instruments for viper are needed for this archive).
 
I think so others can follow, there is a newer github location to get these into the system. It must be new since I have the first pull request. See: https://github.com/NASA-PDS/pds4-context-products/pull/1

Again, happy to go with any version you already have or updates to this pull request. Sorry if I got this out of order.
