### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:gbo.ast.catalina.survey::1.0 SBN PSI CSS Batch D

### ISSUE THREAD

**Issue by beatricemueller** [NASA-PDS/operations#384]
### Discipline Node Information

* **Delivering Node**: _please enter your DN here for record keeping purposes_
* PDS_PSI

* **NSSDCA Delivery Package**: _please upload the files output by PDS Deep Archive as a TAR.GZ or ZIP file here, or supply a URL to download from_
* https://sbnarchive.psi.edu/pds4/surveys/catalina_extras/sips/deltas/sbnpsi_css_batch_d_20230405.zip

* **Validation report**: _please upload a TXT report or screenshot of PDS4 Validate Tool run on your bundle. NSSDCA only accepts valid PDS4 bundles. be sure you run validate with the `-R pds4.bundle` flag enabled to ensure all integrity checks are completed successfully._
* https://sbnarchive.psi.edu/pds4/surveys/catalina_extras/validation/sbnpsi_css_valreports_batch_d.zip

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by beatricemueller** [comment]
@c-suh This CSS delivery includes packages 20220715, 20220722, 20220729, 20220805, 20220812.
Note that the validation report might have errors, but any file that throws an error is pulled and is not submitted and will be submitted subsequently once fixed. This is an acceptable approach as discussed in [#252](https://github.com/NASA-PDS/operations/issues/252)

**Comment by c-suh** [comment]
@beatricemueller the validation reports are missing for package 20220722; please provide these (I will apply your note above to these reports). Thank you!

In the meantime, these 4 sets have been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:gbo.ast.catalina.survey_v1.0_20220715_delta_20230111191550244750
urn:nasa:pds:system_bundle:product_sip_deep_archive:gbo.ast.catalina.survey_v1.0_20220729_delta_20230111191705870212
urn:nasa:pds:system_bundle:product_sip_deep_archive:gbo.ast.catalina.survey_v1.0_20220805_delta_20230111191711684061
urn:nasa:pds:system_bundle:product_sip_deep_archive:gbo.ast.catalina.survey_v1.0_20220812_delta_20230111191719679886

**Comment by beatricemueller** [comment]
@c-suh: Sorry for the oversight. the missing validation report is here:
https://sbnarchive.psi.edu/pds4/surveys/catalina_extras/validation/20220722.tar.gz

**Comment by smclaughlin7** [comment]
@c-suh CSS Batch D had 5 SIPs. I want to confirm this SIP LID was not posted because it only contained one item, the bundle product:

urn:nasa:pds:system_bundle:product_aip:gbo.ast.catalina.survey_v1.0_20220722_delta_20230111191645259219::1.0

Thanks!

**Comment by c-suh** [comment]
@beatricemueller thank you for the tarball; however, it's like its predecessor in the original zip of all validation reports - it unpacks a `20220722` directory which holds an empty `backlog` directory instead of a `backlog` directory of JSON files. @smclaughlin7 correct - that SIP LID was not posted, because I am awaiting its validation reports; however, I am not certain about it containing one item or not.

**Comment by smclaughlin7** [comment]
@beatricemueller Our front-end process marked the collection products in this SIP LIDVID as invalid:

urn:nasa:pds:system_bundle:product_sip_deep_archive:gbo.ast.catalina.survey_v1.0_20220805_delta_20230111191711684061::1.0

Looking at the attached Planet. Sci. Interface report, all the collections have VID 2.0, which is odd and out of sequence with the previous and subsequent SIPs, e.g., 20220729 and 20220812.  Perhaps the VID was supposed to be 200.0?  Jesse may want to check into this.

This SIP was passed to ingest, so we will archive all basic products contained in the SIP manifest.  Since the CSS SIPs keep coming, I suspect it's not worth your effort to remake this SIP just so we can ingest those few collection products.

[CSS_SIP_20220805.pdf](https://github.com/NASA-PDS/operations/files/11519076/CSS_SIP_20220805.pdf)

**Comment by beatricemueller** [comment]
Jesse said to just ignore the 20220722.  For the future, if there is just
the bundle sip and no valid validation report., just ignore it. I hope, it
does not happen that often. I have no way in telling  beforehand.

Beatrice

**Comment by oddes** [comment]
10/16/2023: SIP Status is Ingested.

**Comment by jordanpadams** [comment]
@beatricemueller all packages have been validated by NSSDCA and submitted to Ingest. NSSDCA has now taken responsibility for an additional copy of this data
