### ISSUE TITLE
Test tools using coldfusion for OL8 

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/operations#432]
## 💡 Description

- [x] Subscription Service
- [x] Release Manager
- [ ] Resource Manager
- [x] Catalog Manager

**Comment by jordanpadams** [comment]
@acyu-jpl when you have a chance, can you checkout some of these tools deployed on the new OL8 staging machine?

**Comment by acyu** [comment]
Subscription Service tested.

Able to subscribe and have account created, able to update password, update subscription selection, unsubscribe from subscription, and is getting email notification when subscribed

**Comment by acyu** [comment]
Catalog Manager tested

Able to login and view datasets information.  My account does not have update permission it seems

**Comment by acyu** [comment]
Catalog Manager tested

Able to login, and view and edit. able to create new release object. able to filter list view by mission and instrument

**Comment by c-suh** [comment]
@acyu resource manager has been repackaged and redeployed. Please test again.

**Comment by c-suh** [comment]
(Not coldfusion related but noting this here since it was discovered during this task.) Resource Manager and Data Set Status wasn't working on all pdscloud machines. Talked with SAs and there was a new password. Updated and redeployed these 2 applications, and they work on the el7 machines but not on ol8. Database credentials have been tested on ol8 and are correct, so the issue might have to do with Java 8 to Java 11.

**Comment by c-suh** [comment]
A note that the statuses of the listed applications and Data Set Status are the same as last reported in the comments above.
