### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:co_iss_global-maps

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#462]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[co_iss_global-maps_20231107.tar.gz](https://github.com/NASA-PDS/operations/files/13288610/co_iss_global-maps_20231107.tar.gz)

* **Validation report**: 
[coiss_globalmaps.txt](https://github.com/NASA-PDS/operations/files/13288612/coiss_globalmaps.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by oddes** [comment]
@tinagueth:  This set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:co_iss_global-maps_v1.0_20231107

**Comment by smclaughlin7** [comment]
@tinagueth @c-suh @oddes  Our NSSDCA Ingest process rejected this SIP LID
- urn:nasa:pds:system_bundle:product_sip_deep_archive:co_iss_global-maps_v1.0_20231107

because these two entries in the [SIP manifest](https://pds.nasa.gov/data/pds4/manifests/2023/co_iss_global-maps_v1.0_20231107_sip_v1.0.tab) point to the same data object (URL) but specify two different LIDVIDs:
```
b7e289a933faf94f41eae7096f851692        MD5     https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/co_iss_global-maps/data_derived/Image_Information/Saturn_ISS_RGB_global_map_inf.txt      urn:nasa:pds:co_iss_global-maps:data_derived:cassini_iss_rgb_saturn_global_color_map_contrast_enhance::1.0
b7e289a933faf94f41eae7096f851692        MD5     https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/co_iss_global-maps/data_derived/Image_Information/Saturn_ISS_RGB_global_map_inf.txt      urn:nasa:pds:co_iss_global-maps:data_derived:cassini_iss_rgb_saturn_global_color_map_original::1.0
```
In other words, the same data object https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/co_iss_global-maps/data_derived/Image_Information/Saturn_ISS_RGB_global_map_inf.txt is identified as a component of two different observational products:
```
urn:nasa:pds:co_iss_global-maps:data_derived:cassini_iss_rgb_saturn_global_color_map_contrast_enhance::1.0
urn:nasa:pds:co_iss_global-maps:data_derived:cassini_iss_rgb_saturn_global_color_map_original::1.0
```
PDS4 Standards Reference 2A.3 states “digital objects which comprise observational data may be used in one and only one product”, that is one LID. [Validate Issue 245](https://github.com/NASA-PDS/validate/issues/245) addresses this issue, which we first encountered in MGS TES delivery #263, but it's ETA is TBD.  @jordanpadams

In the interim, possible solutions are to archive the digital object “Saturn_ISS_RGB_global_map_inf.txt” as either

1. a separate basic product, then link to it via a new internal reference in the labels of the two rejected products, or
2. two different digital objects with slightly different names, one for each of the rejected products?

These solutions are the ones I proposed for #263, where you implemented solution 2 and resubmitted a new SIP #321.  Would one of these solutions be acceptable?

**Comment by jordanpadams** [comment]
@smclaughlin7 we are actually working on that check now: https://github.com/NASA-PDS/validate/issues/755

As a note, per your comment, we are only checking this on a per LID basis, not LIDVID. e.g. if someone updates a v1.0 label to v1.1, we do not expect them to create a new product file.

**Comment by smclaughlin7** [comment]
> As a note, per your comment, we are only checking this on a per LID basis, not LIDVID. e.g. if someone updates a v1.0 label to v1.1, we do not expect them to create a new product file.

@jordanpadams Yes, I agree.  SR 2A.3 states “digital objects which comprise observational data may be used in one and only one product”, which I've always assumed to mean LID not LIDVID.  And I believe this was the intent of that rule.

**Comment by tinagueth** [comment]
@c-suh @oddes @smclaughlin7 resubmitted bundle, see #464
