### ISSUE TITLE
[ldd-release] Mars Reconnaissance Orbiter Mission LDD Version: 1310 IM Version: 1L00, 1K00

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#509]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

This is for a HiRISE review, so maybe soon-ish.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-mro/releases

### PDS4 IM Versions to Release

1L00, 1K00

**Comment by c-suh** [comment]
Hi @thareUSGS! Sincere apologies for the delay. There is an error for both these LDDs (see attached reports) regarding a mismatch between the given filesize in the xml file of the xsd file versus the actual filesize of the xsd file. Please address these and let me know once done. Thank you!

[PDS4_MRO_1K00_1310_validate.txt](https://github.com/NASA-PDS/operations/files/15354625/PDS4_MRO_1K00_1310_validate.txt)
[PDS4_MRO_1L00_1310_validate.txt](https://github.com/NASA-PDS/operations/files/15354626/PDS4_MRO_1L00_1310_validate.txt)

**Comment by jordanpadams** [comment]
@c-suh as a heads up, since these LDDs were auto-generated by our software, this just comes right back to us to fix...

@thareUSGS no idea how/what happened here. seems like a random bit flip or something when we move the files from the `development` directory to the `release` directory. No clue. But it seems to be fixed.

@c-suh you should be OK to try posting these again.

**Comment by thareUSGS** [comment]
Thanks. I was going to dig into it but your right I wasn't sure where to look.
