### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:astromat::1.0 and urn:nasa:pds:insight_ida::2.0

### ISSUE THREAD

**Issue by alknight-wustl** [NASA-PDS/operations#519]
### Discipline Node Information

* **Delivering Node**: PDS Geosciences Node

* **NSSDCA Delivery Package**: 
[GEO_Astromat_InSight_delivery_packages_04_June_2024.zip](https://github.com/user-attachments/files/15561257/GEO_Astromat_InSight_delivery_packages_04_June_2024.zip)

* **Validation report**: 
[Astromat_InSight_validate_reports.zip](https://github.com/user-attachments/files/15561363/Astromat_InSight_validate_reports.zip)

**Comment by alknight-wustl** [comment]
The Geosciences Node is aware of the error present in the validation report for urn:nasa:pds:astromat::1.0. The error is caused by a person's name. We are not planning on correcting it at this time.

**Comment by c-suh** [comment]
@alknight-wustl thank you for the heads up about the error. These 2 sets have been posted for NSSDCA processing! From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:astromat_v1.0_20240528
* urn:nasa:pds:system_bundle:product_sip_deep_archive:insight_ida_v2.0_20240528

**Comment by smclaughlin7** [comment]
@alknight-wustl  (and perhaps @jordanpadams)  re: SIP LID urn:nasa:pds:system_bundle:product_sip_deep_archive:astromat_v1.0_20240528

We/NSSDCA would appreciate it if you/Geosciences could provide an explanation why there is no context product (i.e., no Internal_Reference) for Observing_System_Component "Electron Microprobe" in the bundle product, https://pds-geosciences.wustl.edu/lab/urn-nasa-pds-astromat/bundle_astromat_chem.xml?  Perhpas this was intentional?

(We do understand the schema does not require Internal_Reference for Observing_System_Component.)

Thanks!

**Comment by alknight-wustl** [comment]
@smclaughlin7 I believe the Observing_System_Component "Electron Microprobe" was a typical commercial laboratory instrument, and we usually don't create new context products for such instruments.

**Comment by smclaughlin7** [comment]
@alknight-wustl  Thank you. This is good to know.  Our frontend process for PDS4 submissions did not process SIP

- urn:nasa:pds:system_bundle:product_sip_deep_archive:astromat_v1.0_20240528

because it could not find the <Internal_Reference> element (for a Context product) in <Observing_System_Component> in the bundle product.  It assumes the element will be present. (it uses that element to link PDS4 submissions to instrument records in our database.)

This is the first bundle we've received where an Observing_System_Component does not have an associated Context product. Given this and the fact that the IM does not require <Observing_System_Component>.<Internal_Reference>, I'll work with our software dev team to revise our frontend process accordingly.  It may be awhile before they can get to this, so we will keep this SIP at a status of "Proferred" in our system.  Please let me know if this delay will affect updating this bundle in the near future.  (The bundle should not be changed until we have ingested it.)

I'm cc'ing @c-suh and @jordanpadams so they're aware of this delay.
Thanks!

**Comment by alknight-wustl** [comment]
@smclaughlin7 Sounds good! We don't expect to be updating the bundle in the near future, so the delay shouldn't be an issue for us.

**Comment by smclaughlin7** [comment]
@alknight-wustl  Good news! We/NSSDCA enhanced our PDS4 frontend process to continue processing a SIP when a bundle or collection product does not include <Context_Area>, <Observing_System_Component>, or <Observing_System_Component>.<Internal_Reference>.

We successfully reprocessed the outstanding Astromaterials SIP from June through our enhanced frontend.  You check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:

    urn:nasa:pds:system_bundle:product_sip_deep_archive:astromat_v1.0_20240528

I'm cc'ing @c-suh and @jordanpadams so they're aware this issue is resolved.

Thanks for your patience!

**Comment by c-suh** [comment]
@alknight-wustl both sets in this ticket have been archived by NSSDCA.
